/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GVVT6e0qla1
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Judson } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/src/app/(website)/components/ui/select";
import Link from "next/link";

export function EpisodesPage() {
  return (
    <>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-800 text-gray-300">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                  Growing Your Business With People Podcast!
                </h1>
                <p className="max-w-[600px] text-gray-400 md:text-xl">
                  Catch up on the latest episodes.
                </p>
              </div>
            </div>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-1">
              <Select>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select Season" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="season1">Season 1</SelectItem>
                  <SelectItem value="season2">Season 2</SelectItem>
                  <SelectItem value="season3">Season 3</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid grid-cols-1 gap-6 px-4 md:px-6 lg:grid-cols-3 lg:gap-8">
          {/* Start Podcast Card. */}
          <div className=" group relative overflow-hidden rounded-lg bg-white shadow-sm transition-all hover:shadow-lg ">
            <Link
              className="flex flex-col group relative overflow-hidden rounded-lg bg-white shadow-sm transition-all hover:shadow-lg"
              href="#"
            >
              <img
                alt="Episode Image"
                className="aspect-video object-cover w-full"
                height={400}
                src="/placeholder.svg"
                width={600}
              />
              <div className="p-4 sm:p-6">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-semibold tracking-tight">
                    Episode 1: Introduction to Podcasting
                  </h3>
                  <span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium dark:bg-gray-800">
                    S1E1
                  </span>
                </div>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  In this episode, we dive into the world of podcasting and
                  explore the fundamentals of creating a successful podcast.
                </p>
              </div>
            </Link>

            {/* End Podcast Card */}
          </div>
        </div>
      </section>
    </>
  );
}
